# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170810_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TBR_sensorData',
            new_name='TBRsensorData',
        ),
    ]
